project:
  type: website
  output-dir: _site

website:
  title: "Connor Conkey-Morrison"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Research
        href: pages/research.qmd
        menu:
          - text: "Research overview"
            href: pages/research.qmd
          - text: "Current focus"
            href: pages/research.qmd#current-research-focus
          - text: "Publications"
            href: pages/research.qmd#publications
          - text: "PhD papers"
            href: pages/research.qmd#current-research-focus
      - text: Education & Experience
        href: pages/history.qmd
        menu:
          - text: "Current appointments"
            href: pages/history.qmd#current-appointments
          - text: "Education"
            href: pages/history.qmd#education
          - text: "Academic roles"
            href: pages/history.qmd#academic-appointments
          - text: "Clinical roles"
            href: pages/history.qmd#clinical-and-school-based-roles
      - href: pages/projects.qmd
        text: Projects
      - href: pages/contact.qmd
        text: Contact
    right:
      - text: LinkedIn
        href: https://www.linkedin.com/in/connorconkeymorrison

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">
