project:
  type: website
  output-dir: _site

website:
  title: "Connor Conkey-Morrison"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/research.qmd
        text: Research
      - href: pages/history.qmd
        text: Teaching
      - href: pages/contact.qmd
        text: Contact
    right:
      - text: ORCID
        href: https://orcid.org/0009-0000-1020-2333
      - text: Scholar
        href: https://scholar.google.com/citations?user=ZEvUL_kAAAAJ
      - text: LinkedIn
        href: https://www.linkedin.com/in/connorconkeymorrison

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">